apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        # 这里替换成你自己的 Docker Hub 用户名
        image: your-dockerhub-username/java-maven-app:latest 
        ports:
        - containerPort: 8080